services:
  frontend:
    build: .
    container_name: vetra-frontend
    
    ports:
      - "80:80"

    networks:
      - vetra_network

    restart: unless-stopped

networks:
  vetra_network:
    external: true